name: pyrosetta_extensions
channels:
  - defaults
  - conda-forge
  - antonkulaga
  - bioconda
dependencies:
  - python=3.9
  - jupyterlab=3.2.9
  - more-itertools=8.12.0
  - pdbfixer
  - click
  - vmd-python
  - biopython
  - pyrosetta
  - twine
  - pip:
      - pyfunctional
      - tdqm